security:
  jwt:
    expiracao: 24
    chave-assinatura: dmVuZGFz

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: eryck3003
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
      show_sql: true
      format_sql: true

  main:
    allow-circular-references: true
