server:
  port: 8083

security:
  jwt:
    expiracao: 24
    chave-assinatura: dmVuZGFz

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Vendas
    driver-class-name: com.mysql.jdbc
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
      show_sql: true
      format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  main:
    allow-circular-references: true

  security:



