#Configs de conexão com o banco de dados h2
spring.datasource.url = jdbc:h2:mem:testdb
spring.datasource.driveClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.datasource-plataform=org.hibernate.dialect.H2Dialect

#Configs de consulta do banco de dados h2
spring.h2.console.enable=true
spring.h2.console.path=/h2-console

#Mostrar o slq no console
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true