CREATE TABLE Cliente (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR(100),
  CPF VARCHAR (11)
);

CREATE TABLE Produto (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(100),
    PRECO_UNITARIO NUMERIC(20,2)
);

CREATE TABLE Pedido (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CLIENTE_ID INTEGER REFERENCES Cliente(ID),
    DATA_PEDIDO TIMESTAMP,
    STATUS VARCHAR(20),
    TOTAL NUMERIC(20,2)
);

CREATE TABLE Item_Pedido(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    PEDIDO_ID INTEGER REFERENCES Pedido(ID),
    PRODUTO_ID INTEGER REFERENCES Produto(ID),
    QUANTIDADE INTEGER
);